name: Main

on:
  push:
    branches:
      - main
      - FeatureA
      - Dev
  pull_request:
    branches:
      - Dev
      - Main

  
jobs:  
   build:    
     runs-on: [self-hosted, dotnet]

     steps:
     
       - uses: actions/checkout@v2
       
       - name: Setup MSBuild
         uses: microsoft/setup-msbuild@v1

         
       - name: Setup NuGet.exe for use with actions
         uses: NuGet/setup-nuget@v2.0.0
         with:
          nuget-version: '5.x'


       - name: Setup VSTest
         uses: darenm/Setup-VSTest@v1

       - name: Restore Packages
         run: nuget restore Myntra/Myntra.sln
         working-directory: ${{ github.workspace }}


       - name: Build solution
         run: msbuild.exe Myntra/Myntra.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

         working-directory: ${{ github.workspace }}


       - name: Run Tests
         run: vstest.console.exe .\Myntra.Tests\bin\Release\Myntra.Tests.dll
         
       - name: Upload a Build Artifact
         uses: actions/upload-artifact@v4.6.2
         with:
          name: EZRepBundle
          path: "./_build"

          
   deploy:
    name: Deploy to IIS on Azure VM
    runs-on: [self-hosted, VM]
    needs: build
    environment:
      name: Main
      
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: EZRepBundle
          path: Deploy

          
      - name: Ensure IIS site exists (safe, no WebAdministration or site listing)
        shell: powershell
        run: |
          $siteName = "myntra"
          $physicalPath = "C:\Deploy\Myntra"
      
          if (-Not (Test-Path $physicalPath)) {
            New-Item -ItemType Directory -Path $physicalPath -Force | Out-Null
          }
      
          try {
            & "$env:SystemRoot\System32\inetsrv\appcmd.exe" add site /name:"$siteName" /bindings:"http/*:4023:" /physicalPath:"$physicalPath"
            Write-Output "Created IIS site '$siteName'"
          } catch {
            Write-Output "Site might already exist or another error occurred: $_"
          }


      - name: IIS Deploy
        uses: ChristopheLav/iis-deploy@v1.0.0
        with:
           website-name: myntra
           msdeploy-service-url: http://localhost:4023
           msdeploy-username: ${{ secrets.AZURE_VM_USERNAME }}
           msdeploy-password: ${{ secrets.AZURE_VM_PASSWORD }}
           source-path: ${{ github.workspace }}\Deploy\
        
 #     - name: Extract Zip
  #      run: |
   #       Expand-Archive -Path EZRepBundle/WebApp.zip -DestinationPath C:\Deploy\Myntra -Force
