name: Build and Tests

on:  
   push:
     branches: [ main ]
jobs:  
   build:    
     runs-on: dotnet
     
     steps:
     
       - uses: actions/checkout@v2
       
       - name: Setup MSBuild
         uses: microsoft/setup-msbuild@v1

       - name: Setup NuGet
         uses: NuGet/setup-nuget@v5.x

       - name: Setup VSTest
         uses: darenm/Setup-VSTest@v1

       - name: Navigate to Workspace
         run: cd $GITHUB_WORKSPACE

       - name: Restore Packages
         run: nuget restore Myntra.sln

       - name: Build Solution
         run: |
           msbuild.exe Myntra.sln /p:platform="Any CPU" /p:configuration="Release"

       - name: Run Tests
         run: vstest.console.exe .\tests\Myntra.Tests\bin\Release\Myntra.Tests.dll
