name: Main branch CI

on:  
   push:
     branches: [ main ]
jobs:  
   build:    
     runs-on: dotnet
     
     steps:
     
       - uses: actions/checkout@v2
       
       - name: Setup MSBuild
         uses: microsoft/setup-msbuild@v1

         
       - name: Setup NuGet.exe for use with actions
         uses: NuGet/setup-nuget@v2.0.0
         with:
          nuget-version: '5.x'

       - name: Setup VSTest
         uses: darenm/Setup-VSTest@v1

       - name: Restore Packages
         run: nuget restore Myntra/Myntra.sln
         working-directory: ${{ github.workspace }}

       - name: Build Solution
         run: |
           msbuild.exe Myntra.sln /p:platform="Any CPU" /p:configuration="Release"

       - name: Run Tests
         run: vstest.console.exe .\tests\Myntra.Tests\bin\Release\Myntra.Tests.dll
