name: Main branch CI-CD

on:  
   push:
     branches: [ main ]

env:
  ARTIFACT_NAME: drop
  
jobs:  
   build:    
     runs-on: [self-hosted, dotnet]

     steps:
     
       - uses: actions/checkout@v2
       
       - name: Setup MSBuild
         uses: microsoft/setup-msbuild@v1

         
       - name: Setup NuGet.exe for use with actions
         uses: NuGet/setup-nuget@v2.0.0
         with:
          nuget-version: '5.x'

       - name: Setup VSTest
         uses: darenm/Setup-VSTest@v1

       - name: Restore Packages
         run: nuget restore Myntra/Myntra.sln
         working-directory: ${{ github.workspace }}


       - name: Build solution
         run: msbuild.exe Myntra/Myntra.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

         working-directory: ${{ github.workspace }}


       - name: Run Tests
         run: vstest.console.exe .\Myntra.Tests\bin\Release\Myntra.Tests.dll
         
       - name: Upload a Build Artifact
         uses: actions/upload-artifact@v4.6.2
         with:
          name: EZRepBundle
          path: "./_build"

          
   deploy:
    name: Deploy to IIS on Azure VM
    runs-on: [self-hosted, VM]
    needs: build
    environment:
      name: Main
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Download build artifact
        uses: actions/download-artifact@v4.2.1
        with:
         name: drop
         path: 'C:\Deploy\MyntraApp-githubactions'  # Target folder for deployment on VM
      
      - name: Stop IIS website
        run: |
         Import-Module WebAdministration
         Stop-Website -Name "MyntraApp-githubactions"
        shell: powershell

      - name: Deploy files to IIS site
        run: |
         Copy-Item "C:\Deploy\MyntraApp-githubactions\*" "C:\inetpub\wwwroot\MyntraApp-githubactions" -Recurse -Force
        shell: powershell

      - name: Start IIS website
        run: |
         Start-Website -Name "MyntraApp-githubactions"
        shell: powershell
